### ISSUE TITLE
No Group Length available in Meta Information Header

### ISSUE THREAD

**Issue by ClaireDelplancke** [scikit-rt/scikit-rt#1]
When writing an `Image` object to DICOM with `header_source=None`, the field "(0002, 0000) File Meta Information Group Length" in the meta-data header is not created.

This causes an error when trying to open the DICOM folder with AMIDE viewer:
"W: DcmMetaInfo: No Group Length available in Meta Information Header"

**Comment by kh296** [comment]
I believe this is now fixed.  Could you try with the updated code?

**Comment by ClaireDelplancke** [comment]
I still cannot open the DICOM folder with AMIDE viewer, but the error message has changed, I now get:
"** (process:30239): DEBUG (recursed): Name com.canonical.AppMenu.Registrar does not exist on the session bus
Aborted"

Will update AMIDE and report back.

**Comment by ClaireDelplancke** [comment]
I already had the last version of AMIDE actually. Does it work for you @kh296 ?

**Comment by kh296** [comment]
On MacOS, AMIDE loaded and displayed the DICOM image, but with a couple of problems:

1. Intensity values were effectively being written as integers, meaning that values were either 0 or 1 for the PET image!  This is now corrected in `scikit-rt`.
2. The DICOM image produced by `scikit-rt` from the example NIfTI image has some negative spacings.  There's nothing intrinsically wrong with this (it basically relates to the axis orientations), but AMIDE isn't able to handle the negative values, and sets the voxel size to 1 in all dimensions.  This could be corrected in `scikit-rt`, but it would be better to change at the level of the NIfTI image.  If you let me know how the DICOM image should display, I can try to work out how the axes and affine matrix of the NIfTI image need to be changed.

Independently of the above, on which platform are you seeing the error?  Can you provide some sample DICOM data that AMIDE is able to read there?

**Comment by ClaireDelplancke** [comment]
I see the error on Ubuntu. I'll send you some data directly.

**Comment by ClaireDelplancke** [comment]
FYI here's how I use the conversion code:
https://github.com/ClaireDelplancke/SIRF-pipeline/blob/master/src/utils.py#L253
